services:
  app:
    image: washamga/extracurricular-cs4116:latest
    ports:
      - 5173:5173
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      ORIGIN: ${ORIGIN}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
networks: {}